.eslintrc.json, .github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md, .github/PULL_REQUEST_TEMPLATE.md, .github/workflows/pr-title-linter-and-linker.yml, .github/workflows/stale.yml, .husky/pre-commit, .lintstagedrc.js, package.json, src/app/[locale]/(pages)/ko/page.tsx, src/app/[locale]/(pages)/profileRestore/page.tsx, src/app/[locale]/(pages)/restoreCode/page.tsx, src/app/[locale]/_hooks/useLogin.tsx, yarn.lock
Add github actions, templates and husky pre commit configurations using lint
=> [IOPID-478] : create github actions and template and lint configuration

src/app/[locale]/_component/noProfile/noProfile.tsx, src/app/[locale]/_utils/api-utils.ts, src/app/[locale]/_utils/routes.ts, src/app/[locale]/page.tsx
Moved /nessun-profilo Page into Profile Page as a component 
- Moved /nessun-profilo Page into Profile Page as a component
1. Login as L2
2. Mock the GetProfile Api response with Moockon to return status code 404
=> [IOPID-694] : noProfile component in profile page

src/app/[locale]/(pages)/500/page.tsx, src/app/[locale]/_component/feedbackMessage/feedbackMessage.tsx, src/app/[locale]/_hooks/__tests__/usePushBack.test.tsx, src/app/[locale]/_hooks/usePushBack.tsx, src/app/[locale]/_utils/routes.ts
Created 500 error page
- New static 500 error page
- Updated Box maxWidth to 500px according to Figma (Feedback Message component)
- Added to Feedback Message component the "push to previous page" button
yarn run build
check that in the folder out/it exist the static 500.html page
-yarn run start-static
go to /it/500
=> [IOPID-706] : 500 Error Page 

src/app/[locale]/_component/header/header.tsx, src/app/[locale]/_hooks/__tests__/useLogin.test.tsx, src/app/[locale]/_hooks/useLogin.tsx
This modification introduces the dropdown menu for the logged-in user.
- Added User Menu
- User Menu functionalities (**Logout** and go to **Profile**)
Run the project and log in with hub spid login.
If you access with L1, the menu will only have the option LOGOUT.
If you access with L2, the menu will have the PROFILE and LOGOUT options.
=> [IOPID-695] : User Menu

src/app/[locale]/_component/feedbackMessage/__test__/feedbackMessage.test.tsx
Unit test for FeedbackMessage component
Run> **yarn run test -- feedbackMessage.test.tsx**
=> [IOPID-733] : FeedbackMessage component Unit Test

src/app/[locale]/_component/selectIdp/idpList.tsx, src/app/[locale]/_utils/integrity.ts
Update hashing algorithm to SHA256
=> [IOPID-865] : Update hashing algorithm

src/app/[locale]/(pages)/accedi/errore/page.tsx, src/app/[locale]/(pages)/accedi/page.tsx, src/app/[locale]/(pages)/esci/page.tsx, src/app/[locale]/_component/selectIdp/idpList.tsx, src/app/[locale]/_model/LoginAttempt.ts, src/app/[locale]/_model/LoginInfo.ts, src/app/[locale]/_utils/common.ts, src/app/[locale]/_utils/storage.ts
Adding Mixpanel Track Event for Login Flow, including login error page
Run the project and check the console for the tracked event (mixpanel mocked), as specified in Figma, for the login flow.
Note:
To test the error login page:
- Try to login with hubspid login
- Instead of insert login and password click on "Ignore" on hub spid login page
- You will be redirected to error page
=> [IOPID-836] : Mixpanel Login Flow

src/app/[locale]/(pages)/404/page.tsx, src/app/[locale]/(pages)/500/page.tsx, src/app/[locale]/_component/header/header.tsx, src/app/[locale]/_utils/mixpanel.ts
Adding Mixpanel to Track Event on 400 & 500 page
Run the project and check the console for the tracked event (mixpanel mocked), as specified in Figma, for 404 & 500 pages.
We took advantage of this PR to adjust mixPanel utils, adding on trackEvent the condition on window object to check if is initialized.
=> [IOPID-902] : Mixpanel 404 & 500

src/app/[locale]/_component/header/header.tsx
Showing support button only if the user is logged
Run the project, verify if "Assistenza" button is available on header only if user is logged
=> [IOPID-910] : Showing Support button only if is logged

.devops/deploy-pipelines.yml
=> [#IOPID-928] fix: service endpoint name

.devops/deploy-pipelines.yml, src/app/[locale]/_utils/idps.ts
[[#IOPID-928] fix: env var incorrect evaluation](https://github.com/pagopa/io-web-profile/commit/c03bd760fbc36370ed85625c88a9ecebd9ebb189)
[[#IOPID-928] fix: release title doesn't include version](https://github.com/pagopa/io-web-profile/commit/52437f25f9a60d14b9161aefc4014a7015c15509)
=> [#IOPID-928]  fixes

public/login/io-esco-cie.signed.xml, public/login/io-esco-spid.signed.xml
Adding metadata files to **public/login** folder
=> [IOPID-954] : Adding Metadata 

mock/mockoon_api.json, src/app/[locale]/(pages)/blocco-accesso/page.tsx, src/app/[locale]/(pages)/ripristino-accesso/accedi-livello-2/page.tsx, src/app/[locale]/(pages)/ripristino-accesso/inserisci-codice/page.tsx, src/app/[locale]/_component/profileCards/restoreSessionCard.tsx, src/app/[locale]/_component/selectIdp/idpList.tsx, src/app/[locale]/_hooks/useToken.tsx, src/app/[locale]/_utils/routes.ts, src/dictionaries/it.json
Adjustment for Magic Link Flow
1. Run Mockoon (new mock file in pr).
2. Run the Project.
3. Access using the magic link, e.g., http://localhost:3000/it/blocco-accesso/magic-link/#token=token.
4. Click on the "Continue" button.
5. Click on the "Block Access" button.
6. When the profile is locked, click on the "Return to Profile" button.
7. On the profile page, click on the "Unlock Access" card button.
8. You should see the new page **http://localhost:3000/it/ripristino-accesso/accedi-livello-2/**
=> [IOPID-952] : MagicLink Flow Adjustment 

.env, .env.example, .env.local, .env.test.local
=> [IOPID-942] : Update BackToHome Link

public/login/spid-metadata.xml
- Add `md` namespace, update certificate
=> fix: Add `md` namespace, update certificate to spid-metadata.xml

public/login/cie-metadata.xml
Align CIE Metadata to SPID one, by updating certificate, info and signature
=> Update CIE Metadata with new certificate and info

src/app/[locale]/(pages)/404/page.tsx, src/app/[locale]/(pages)/accesso-bloccato/page.tsx, src/app/[locale]/(pages)/ripristino-accesso/inserisci-codice/page.tsx, src/app/[locale]/_component/accordion/faqDefault.tsx, src/app/[locale]/_component/header/header.tsx, src/app/[locale]/_component/selectIdp/idpList.tsx
During build the window function crush. To fix it I add into all the project, when window function is called, the function isBrowser(). This function control if window is different from undefined 
- add in all occurence of window function the control using function isbrowser()
test using command `yarn next build`
=> fix [IOPID-1039] problem on window

src/app/[locale]/(pages)/esci/page.tsx, src/app/[locale]/(pages)/ripristino-accesso/errore/page.tsx, src/app/[locale]/_component/sessionActiveComp/sessionActiveComp.tsx, src/app/[locale]/_utils/idps.ts
Changes described in the various tasks
[IOPID-1249] : MixPanel Event Confirm Logout
[IOPID-1169] : Mixpanel Error TrackEvent
[IOPID-1247] : Mixpanel Tracking Event Login CIE 
[IOPID-1249]: https://pagopa.atlassian.net/browse/IOPID-1249?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[IOPID-1169]: https://pagopa.atlassian.net/browse/IOPID-1169?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[IOPID-1247]: https://pagopa.atlassian.net/browse/IOPID-1247?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [IOPID-1250]  : Mixpanel Fixes

src/app/[locale]/_component/noProfile/noProfile.tsx
Change button label as shown in this [figma](https://pagopa.atlassian.net/browse/IOPID-1300)
=> [IOPID-1300] change button label

src/app/[locale]/_component/accordion/faqDefault.tsx, src/app/[locale]/_component/listComponents/ListComponents.tsx
During tests, inconsistencies were identified in the size of characters in the footer, as described [here.](https://pagopa.atlassian.net/browse/IOPID-1392)
The objective of this pull request (PR) is to adjust the size of the footer using a utility function.
Run the project and verify the fontsize on FAQ (footer)
=> [IOPID-1392] : Footer FontSize Adjustment

src/app/[locale]/(pages)/accesso-bloccato/page.tsx, src/app/[locale]/(pages)/blocco-accesso/operazione-completata/page.tsx, src/app/[locale]/(pages)/ripristino-accesso/accedi-livello-3/page.tsx
deletion of comments on links
- Decomment links directed to io.italia.it
run the application and test link of L3 in these screens: 
http://localhost:3000/it/accesso-bloccato/
http://localhost:3000/it/blocco-accesso/operazione-completata/
http://localhost:3000/it/ripristino-accesso/accedi-livello-3/
=> [IOPID-1231] enabling links

src/app/[locale]/_component/footer/footer.tsx
change link to accessibility declaration button in footer
run the application and click on "Accessibilità" into the footer, before and after login
=> [IOPID-1421] change link to accessibility button in footer

src/app/[locale]/(pages)/accedi/page.tsx, src/dictionaries/it.json
=> [IOPID-1425] change copy of landing page 

src/app/[locale]/(pages)/accedi/page.tsx, src/dictionaries/it.json
delete "Accedi" label in cad with login buttons
=> [IOPID-1427] update copy and delete login title 

package.json, src/app/[locale]/(pages)/404/page.tsx, src/app/[locale]/(pages)/blocco-accesso/magic-link/page.tsx, src/app/[locale]/(pages)/blocco-accesso/page.tsx, src/app/[locale]/(pages)/ripristino-accesso/inserisci-codice/page.tsx, src/app/[locale]/_component/accordion/faqDefault.tsx, src/app/[locale]/_component/footer/footer.tsx, src/app/[locale]/_component/header/header.tsx, src/app/[locale]/_component/sessionActiveComp/__tests__/sessionActiveCompENLocale.test.tsx, src/app/[locale]/_component/sessionActiveComp/__tests__/sessionActiveCompITLocale.test.tsx, src/app/[locale]/_component/sessionActiveComp/sessionActiveComp.tsx, src/app/[locale]/_utils/common.ts, src/app/[locale]/page.tsx
fix double click error 403 (after one click disabled button) and fix date format (now the date depends on the data about language read from the local storage)
<p>
| correct date format | button disabled |
| - | - |
| <img width="1293" alt="image correct date" src="https://github.com/pagopa/io-web-profile/assets/83651704/b0b141c0-c8c7-4b63-b794-2271bbdc9661">  | <video src="https://github.com/pagopa/io-web-profile/assets/83651704/eea1995e-40c4-454c-9766-fc923340fae8" /> |
| HOW TO TEST | HOW TO TEST |
| Run the application and in profile section see the correct date | Run the application from this link (http://localhost:3000/it/blocco-accesso/magic-link/#token=token) |
</p>
=> [IOPID-1434] [IOPID-1432] fix double click error 403 and fix date format

src/api/webProfileApiClient.ts, src/app/[locale]/(pages)/accedi/page.tsx, src/app/[locale]/(pages)/blocco-accesso/magic-link/page.tsx, src/app/[locale]/(pages)/blocco-accesso/page.tsx, src/app/[locale]/(pages)/esci/conferma/page.tsx, src/app/[locale]/(pages)/ripristino-accesso/inserisci-codice/page.tsx, src/app/[locale]/(pages)/ripristino-accesso/page.tsx, src/app/[locale]/_component/loader/loader.tsx, src/app/[locale]/_component/sessionActiveComp/sessionActiveComp.tsx, src/app/[locale]/_utils/jwt.ts, src/app/[locale]/_utils/styles.ts, src/app/[locale]/layout.tsx, src/app/[locale]/loading.tsx, src/app/[locale]/page.tsx
The purpose of this PR is to add the spinner in those points where an API is called, as requested in the [task](https://pagopa.atlassian.net/browse/IOPID-1327).
- Spinner Overlay 
Build the package and start the project using the created **static export.**
Modify the timedelay of the calls on Mockoon to simulate an API latency time.
Start the project and try navigating
Here is the video, sorry for the slowness and performance issues, which are caused by my environment.
[screen-capture.webm](https://github.com/pagopa/io-web-profile/assets/145718190/7e3118d6-6461-4af6-86e5-810d5a608e3a)
=> [IOPID-1327] : Spinner 

src/dictionaries/it.json
change copy of first FAQ of lock access
Run the application and make the lock access flow. Look at the FAQ
=> [IOPID-1456] change copy of first FAQ of lock access

src/dictionaries/it.json
Change copy (import new file from ditto)
1. Generate a local build of the application. 
2. Run the build and [hub-spid-login-ms](https://github.com/pagopa/hub-spid-login-ms/tree/master)
3. Try to log and before proceed click on "Annulla" button (from hub-spid-login-ms screens). You will be redirected on this project and the screen displayed will be error 22
=> [IOPID-1651]: change copy SPID error 22

src/api/webProfileApiClient.ts, src/app/[locale]/(pages)/404/page.tsx, src/app/[locale]/(pages)/500/page.tsx, src/app/[locale]/(pages)/esci/conferma/page.tsx, src/app/[locale]/(pages)/esci/errore/page.tsx, src/app/[locale]/(pages)/esci/operazione-completata/page.tsx, src/app/[locale]/_component/header/header.tsx, src/app/[locale]/_component/idpListOnApp/idpListOnApp.tsx, src/app/[locale]/_component/selectIdp/idpList.tsx, src/app/[locale]/_component/sessionProvider.tsx, src/app/[locale]/_hooks/useLocalePush.tsx, src/app/[locale]/_hooks/useToken.tsx, src/app/[locale]/page.tsx
Fixed warning during next lint
See above.
next lint
=> [SIW-1060] Fix lint warning

src/api/webProfileApiClient.ts, src/app/[locale]/(pages)/accedi/page.tsx, src/app/[locale]/(pages)/blocco-accesso/link-scaduto/page.tsx, src/app/[locale]/(pages)/blocco-accesso/magic-link/page.tsx, src/app/[locale]/(pages)/blocco-accesso/operazione-completata/page.tsx, src/app/[locale]/(pages)/esci/conferma/page.tsx, src/app/[locale]/(pages)/esci/page.tsx, src/app/[locale]/(pages)/ripristino-accesso/accedi-livello-2/page.tsx, src/app/[locale]/(pages)/ripristino-accesso/accedi-livello-3/page.tsx, src/app/[locale]/(pages)/ripristino-accesso/inserisci-codice/page.tsx, src/app/[locale]/(pages)/ripristino-accesso/page.tsx, src/app/[locale]/_component/accordion/faqDefault.tsx, src/app/[locale]/_component/footer/footer.tsx, src/app/[locale]/_component/idpListOnApp/idpListOnApp.tsx, src/app/[locale]/_component/selectIdp/selectIdp.tsx, src/app/[locale]/_hooks/useConsent.tsx, src/app/[locale]/_styles/cookieBanner.css, src/app/[locale]/_styles/privacyPage.css, src/app/[locale]/_utils/__tests__/storage-utils.test.tsx, src/app/[locale]/_utils/__tests__/storage.test.tsx, src/app/[locale]/_utils/common.ts, src/app/[locale]/_utils/cookie-utils.ts, src/app/[locale]/_utils/jwt.ts, src/app/[locale]/_utils/onetrust.ts, src/app/[locale]/_utils/routes.ts, src/app/[locale]/_utils/storage-utils.ts, src/app/[locale]/layout.tsx, src/app/[locale]/page.tsx
Executed code linting on the whole code base
=> [SIW-1131] Codebase Linting

src/app/[locale]/(pages)/revoca-wallet/operazione-completata/page.tsx, src/app/[locale]/(pages)/revoca-wallet/page.tsx, src/app/[locale]/_component/accordion/faqDefault.tsx, src/app/[locale]/_component/profileCards/profileCards.tsx, src/app/[locale]/page.tsx, src/dictionaries/it.json
Since the copy management for the Wallet section is not yet available on Ditto, these copies have been moved to a separate section within the JSON file in the io-web-profile project. This is to avoid conflicts when the content management will be handled in the Ditto project.
=> [SIW-1157]  Handling Wallet Section Copy 

src/dictionaries/it.json
Updated it dictionary json file
- Feature A
- Feature B
Describe the tests that you ran to verify your changes. Provide instructions so we can reproduce.
=> chore: [SIW-1396] update it dictionary

src/app/[locale]/_component/homeWalletCard/__test__/home-wallet-card.test.tsx, src/app/[locale]/_component/homeWalletCard/index.tsx
Updated dictionary key to wallet revoked message
- Feature A
- Feature B
Describe the tests that you ran to verify your changes. Provide instructions so we can reproduce.
=> fix: [SIW-1396] update not active wallet message

src/app/[locale]/_component/footer/footer.tsx
- Change links on footer
| as-is | new | 
| - | - |
| <video src="https://github.com/user-attachments/assets/26458f2a-511b-491d-9a61-a2886a30e383" /> | <video src="https://github.com/user-attachments/assets/a5739a2f-b27e-4e1c-b104-7836ca412f7b" /> | 
Run the application and into the footer (before or after login, it's the same) control if "accessibility" link works as you can see from the demo
=> [IOPID-2283] Edit old accessibility links 

.github/workflows/bump-release.yml
Include a summary of the changes.
- Remove bump-release template, use npm instead
Describe the tests that you ran to verify your changes. Provide instructions so we can reproduce.
=> fix: bump release step
